#%RAML 1.0 ResourceType
get:
  description: the resource <<resourcePathName>> not found
  responses:
    501:
      body:
        application/json:
          example:
            {
              message: "<<resourcePath>> server failed for response ! "
             }