#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/1bab0043-dbef-40cf-8911-3335ab26a88f/ # 
title: craft-online-shopping
version: 1.0
types:
  users: !include dataTypes/user.raml
  products: !include dataTypes/product.raml
  order: !include dataTypes/order.raml
traits:
    responseMessages: !include traits/responses.raml
/users:
  description: get all users
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/users.json
  is: [responseMessages]          
              
      
  post:
    description: creates user
    responses:
      200:
        body:
          application/json:
            example:
              {
                "uid": 111
              }          
      201:
        body:
          application/json:
            example:
              {
                "message": "Created"
              }
          
  
    is: [responseMessages]        


  /{userid}:
    description: get user by id
    get:
      responses:
        200:
          body:
            application/json:
              example:  !include examples/user.json
    is: [responseMessages]          
                
/products:
  description: get all products
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/products.json
             
    is: [responseMessages] 
  /{productid}:
    get:
      description: get single product
      responses:
        200:
          body:
            application/json:
              example: !include examples/product.json
                
      is: [responseMessages]  
/orders:
  get:
    description: get all orders
    responses:
      200:
        body:
          application/json:
            example: !include examples/orders.json
              
    is: [responseMessages]  
  post:
    description: creates order
    responses:
      200:
        body:
          application/json:
            example:
              {
                "addressid": 3589068800000,
                "amount": 2000,
                "created": 4589068800000,
                "discountid": 000,
                "modified": 1589068800000,
                "orderid": 100,
                "status": ok,
                "userid": 1000
              }        
      201:
        body:
          application/json:
            example:
              {
                "message": "Created"
              }
          
    is: [responseMessages]                             
  /{orderid}:
    get:
      description: get orders by userid
      responses:
        200:
          body:
            application/json:
              example: !include examples/order.json
                
      is: [responseMessages]     
  /{userid}:
    get:
      description: get orders by userid
      responses:
        200:
          body:
            application/json:
              example: !include examples/user.json
                
      is: [responseMessages]  
/categories:
  get:
    description: find all categories
    responses:
      200:
        body:
          application/json:
            example: !include examples/categories.json
             
    is: [responseMessages]  
  /{categoryid}:
    get:
      description: find category
      responses:
        200:
          body:
            application/json:
              example: !include examples/categories.json
                
      is: [responseMessages]  
      
