#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: This Api support oauth 2.0 
describedBy:
  headers:
    Authorization: 
     description: user have to send token to acces any resoures
     type: string
  queryParameters:
    acces_token:
      description: user have to send valid token with query parameter
      type: string
  responses:
    401:
      body:
        application/json:
          example:
            {
              message: "bad or expired token is used"
            }
    403:
      description: not allowed to acces the resourse