#%RAML 1.0 NamedExample
postorders: 
 {
  "orderid": 1328,
  "userid": 1038,
  "addressid": 201,
  "discountid": 1,
  "created": 1596325228541,
  "modified": null,
  "status": "Accepted",
  "amount": 1000
}