#%RAML 1.0 NamedExample
[{
                  "userid": 901,             
                  "email": "mathew1234@yahoo.com",
                  "date_joined": 1589068800000,
                  "modified": 1586044800000,
                  "type": 1,
                  "deleted": "false",
                  "username": "Mathew",
               },
               {
                  "userid": 902,             
                  "email": "tedg@gmail.com",
                  "date_joined": 1589068800000,
                  "modified": 1586044800000,
                  "type": 2,
                  "deleted": "false",
                  "username": "Ted",
                  
               },      
              {
                  "userid": 1000,
                  "email": "Betty@gmail.com",
                  "date_joined": 1589068800000,
                  "modified": 1586044800000,
                  "type": 3,
                  "deleted": false,
                  "username": "Betty"
              }]