#%RAML 1.0 Trait
  401: 
        body:
          application/json:
        
            example:
               {
                "message": "unauthorized request"
              }
              
  403:
        body:
          application/json:
              
            example:
              {
                "Message": "Forbidden "
              }
        
  404:
        body:
          application/json:
            example:
              {
               "message": "Not found "
              }