#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: this is api support oauth 2.0 security
describedBy:
  headers:
    Authorization: 
      description: users have to send token to acess any resource
      type: string
  queryParameters:
    access_token:
      description: user have to send valid token w/h the querypar
      type: string
  responses:
    401:
      body:
        application/json:
          example:
            {
              message:"bad or expired token is used"
            }
    403:
      description: not allowed to access the resource
